# Generated by Django 4.1.7 on 2023-03-12 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=0)),
                ('title', models.CharField(default='Some title', max_length=250, verbose_name='title')),
                ('description', models.TextField(default='Some text...', verbose_name='description')),
                ('address', models.CharField(default='Some address', max_length=250, verbose_name='address')),
                ('address_link', models.URLField(verbose_name='address_url')),
                ('image', models.ImageField(upload_to='items/%Y/%m/%d/', verbose_name='image')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('author', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.categoryitem', verbose_name='category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('rating',),
            },
        ),
        migrations.CreateModel(
            name='ItemThroughIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ip')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.ManyToManyField(blank=True, through='item.ItemThroughIp', to='main.ip'),
        ),
    ]
